#!/usr/bin/env bash
#
# worktree.sh — isolated git worktrees with their own Docker Compose stacks.
#
set -euo pipefail

OVERRIDE_FILE="docker-compose.override.yml"

# Optional command prefix for every `docker compose` invocation. Repos whose
# compose files need env injected (varlock, dotenvx, sops...) export this from
# .worktree-setup.sh, e.g.
#   export WORKTREE_COMPOSE_WRAPPER="varlock run --no-redact-stdout --"
# Left empty, compose is called directly. Split into an array with the shell's
# own word splitting rather than expanded unquoted at each call site, so the
# behaviour does not depend on the caller's shell (zsh does not split unquoted
# parameters at all, which turns the whole prefix into one command name).
COMPOSE_WRAPPER="${WORKTREE_COMPOSE_WRAPPER:-}"
COMPOSE_PREFIX=()
[ -n "$COMPOSE_WRAPPER" ] && read -r -a COMPOSE_PREFIX <<< "$COMPOSE_WRAPPER"

# ${arr[@]+"${arr[@]}"} rather than "${arr[@]}": on bash 3.2 (still /bin/bash on
# macOS) expanding an empty array under `set -u` is an unbound-variable error.
compose() { ${COMPOSE_PREFIX[@]+"${COMPOSE_PREFIX[@]}"} docker compose "$@"; }

# Re-derives COMPOSE_PREFIX after a .worktree-setup.sh has been sourced. The
# array above is built once at startup from the environment, so a wrapper the
# setup script exports would otherwise never reach compose() — the stack then
# comes up with every interpolated value blank, reports healthy, and serves
# 200, so nothing surfaces the failure.
load_worktree_setup() {
  [ -f .worktree-setup.sh ] || return 0
  # shellcheck source=/dev/null
  . ./.worktree-setup.sh
  COMPOSE_WRAPPER="${WORKTREE_COMPOSE_WRAPPER:-$COMPOSE_WRAPPER}"
  COMPOSE_PREFIX=()
  [ -n "$COMPOSE_WRAPPER" ] && read -r -a COMPOSE_PREFIX <<< "$COMPOSE_WRAPPER"
  return 0
}

# ---------------------------------------------------------------- helpers ---

die() { echo "error: $*" >&2; exit 1; }

require() {
  local missing=()
  for c in "$@"; do command -v "$c" >/dev/null 2>&1 || missing+=("$c"); done
  if [[ " $* " == *" docker "* ]]; then
    docker compose version >/dev/null 2>&1 || missing+=("docker-compose-plugin")
  fi
  # `${#arr[@]}` is safe on an empty array even under `set -u` in bash 3.2
  # (macOS). `${arr[*]}` is NOT, so the die path expands with a `:-` fallback.
  if [ ${#missing[@]} -gt 0 ]; then
    die "missing dependencies: ${missing[*]:-}"
  fi
}

# Sets ROOT, NAME, SLUG, DIR, PROJECT for a branch. Single source of truth for
# how a branch name maps to a directory and a Compose project.
resolve() {
  local branch="$1" from="${2:-.}"
  # ROOT is always the MAIN checkout, never a linked worktree: NAME derives from
  # it and feeds the Compose project name, which has to stay identical whether
  # resolve is called from the main checkout or from inside a worktree.
  # --git-common-dir points every worktree at the shared .git, so its parent is
  # the main checkout; --show-toplevel would return the worktree itself and
  # double the slug in PROJECT.
  local common
  common="$(git -C "$from" rev-parse --path-format=absolute --git-common-dir)" \
    || die "not inside a git repo"
  ROOT="$(dirname "$common")"
  NAME="$(basename "$ROOT")"
  SLUG="$(printf '%s' "$branch" | tr '[:upper:]/' '[:lower:]-' | tr -cd '[:alnum:]-')"
  [ -n "$SLUG" ] || die "branch name '$branch' produced an empty slug"
  DIR="$ROOT/../worktrees/$NAME-$SLUG"
  PROJECT="$NAME-$SLUG"
}

# Porcelain status for a worktree, ignoring the override file we generate.
dirty() {
  git -C "$1" status --porcelain 2>/dev/null \
    | grep -v "^?? $OVERRIDE_FILE\$" || true
}

# Reads the resolved compose config and emits an override that republishes
# every fixed host port on a kernel-assigned one. Run from inside the worktree.
generate_override() {
  # stderr is captured separately: compose emits warnings there (unset variables
  # and the like) and folding them into stdout corrupts the JSON jq then parses.
  local config errfile rc=0
  errfile="$(mktemp)"
  config="$(compose config --format json 2>"$errfile")" || rc=$?
  if [ "$rc" -ne 0 ]; then
    local err; err="$(cat "$errfile")"; rm -f "$errfile"
    die "docker compose config failed:"$'\n'"$err"
  fi
  rm -f "$errfile"

  local body
  body="$(printf '%s' "$config" | jq -r '
    [ .services // {} | to_entries[]
      | select((.value.ports // []) | length > 0)
      | "  \(.key):\n    ports: !override ["
        + ([ .value.ports[]
             | "\"\(.target)" + (if .protocol == "udp" then "/udp" else "" end) + "\""
           ] | join(", "))
        + "]"
    ] | join("\n")
  ')"

  if [ -z "$body" ]; then
    echo "note: no services publish host ports — no override needed" >&2
    return 0
  fi

  {
    echo "# Generated by worktree.sh — do not commit, do not edit."
    echo "# Republishes every host port on a kernel-assigned one so parallel"
    echo "# worktrees don't collide. Regenerated on each spawn."
    echo "services:"
    printf '%s\n' "$body"
  } > "$OVERRIDE_FILE"

  echo "generated $OVERRIDE_FILE"
}

# ------------------------------------------------------------------ usage ---

usage() {
  cat <<'EOF'
worktree.sh — isolated git worktrees with their own Docker Compose stacks

USAGE
  worktree.sh spawn <branch> [base-ref]   create worktree + branch, start stack
  worktree.sh teardown <branch>           stop stack, remove worktree + branch
  worktree.sh reap                        list worktrees whose PR is merged/closed
  worktree.sh list                        list all worktrees and stack status
  worktree.sh help                        this text

SPAWN
  Creates ../worktrees/<repo>-<slug> from <base-ref> (default: main), runs the
  repo's .worktree-setup.sh if present, generates a docker-compose.override.yml
  that republishes every host port on a kernel-assigned one, brings up the
  stack under an isolated project name, and prints the ports Docker assigned.

  The override is generated inside the worktree only — your main checkout keeps
  its usual fixed ports. Nothing needs configuring per repo.

TEARDOWN
  Refuses if the worktree has uncommitted changes. Otherwise removes containers,
  volumes, the worktree, and the local branch. cd back to the main checkout
  afterwards — your working directory will no longer exist.

REPO SETUP (optional)
  .worktree-setup.sh     run inside the fresh worktree before the stack starts;
                         dependency install, secret loading, seeding, etc.

  Add docker-compose.override.yml to .gitignore if it isn't already. Spawn
  refuses to overwrite one that is committed to the repo.

  If the repo's compose files need env injected before docker can read them,
  export a command prefix from .worktree-setup.sh:

    export WORKTREE_COMPOSE_WRAPPER="varlock run --no-redact-stdout --"

  Every `docker compose` call is then made through it. Note that a secrets
  wrapper may redact its own stdout by default, which corrupts the config JSON
  this script parses (a service name colliding with a secret value comes back
  as `db*****`) — pass whatever flag disables that, as above.

REQUIRES
  git 2.31+ (for rev-parse --path-format), docker (compose plugin 2.24+, for
  the !override tag), jq.
  gh is needed for reap and for opening PRs.
EOF
}

# --------------------------------------------------------------- commands ---

cmd_reap() {
  for c in git gh; do
    if ! command -v "$c" >/dev/null 2>&1; then
      echo "warning: $c not found — skipping stale-worktree check" >&2
      [ "$c" = gh ] && echo "         gh is also needed later for 'gh pr create'." >&2
      return 0
    fi
  done

  local root found=0 dir branch state flag
  root="$(git rev-parse --show-toplevel 2>/dev/null)" || return 0

  while read -r dir; do
    [ "$dir" = "$root" ] && continue
    branch="$(git -C "$dir" symbolic-ref --short HEAD 2>/dev/null)" || continue

    state="$(gh pr view "$branch" --json state -q .state 2>/dev/null || echo "")"
    [ "$state" = "MERGED" ] || [ "$state" = "CLOSED" ] || continue

    if [ "$found" = 0 ]; then echo "Stale worktrees:"; found=1; fi

    flag=""
    [ -n "$(dirty "$dir")" ] && flag="  ** UNCOMMITTED CHANGES **"
    echo "  $branch — PR $state$flag"
  done < <(git worktree list --porcelain | awk '/^worktree /{print $2}')

  [ "$found" = 1 ] && { echo "Run: worktree.sh teardown <branch>"; echo; }
  return 0
}

cmd_list() {
  require git docker jq
  local root dir branch up
  # Same reason as resolve(): the main checkout is the parent of the shared
  # .git, so this labels correctly even when run from inside a worktree.
  root="$(dirname "$(git rev-parse --path-format=absolute --git-common-dir)")"
  while read -r dir; do
    branch="$(git -C "$dir" symbolic-ref --short HEAD 2>/dev/null || echo '(detached)')"
    if [ "$dir" = "$root" ]; then
      echo "  $branch — $dir (main checkout)"
    else
      resolve "$branch" "$dir"
      up="$(compose ls --filter "name=$PROJECT" --format json 2>/dev/null \
            | jq -r '.[0].Status // "stopped"')"
      echo "  $branch — $dir [$up]"
    fi
  done < <(git worktree list --porcelain | awk '/^worktree /{print $2}')
}

cmd_spawn() {
  local branch="${1:-}" base="${2:-main}"
  [ -n "$branch" ] || die "usage: worktree.sh spawn <branch> [base-ref]"
  require git docker jq

  resolve "$branch"
  [ -e "$DIR" ] && die "$DIR already exists"

  cmd_reap || true

  git -C "$ROOT" fetch --quiet origin "$base" || true
  git -C "$ROOT" worktree add -b "$branch" "$DIR" "$base"
  cd "$DIR"

  if [ -f "$OVERRIDE_FILE" ]; then
    cd "$ROOT"
    git worktree remove --force "$DIR"
    git branch -D "$branch" 2>/dev/null || true
    die "$OVERRIDE_FILE is committed to this repo — worktree.sh needs to generate it.
       Move its contents into your base compose file or a differently named
       override, gitignore $OVERRIDE_FILE, then try again."
  fi

  export COMPOSE_PROJECT_NAME="$PROJECT"
  # Sourced, not executed: a `bash x.sh` subshell would discard the wrapper the
  # setup script exports. Must run before generate_override, which shells out to
  # `docker compose config`.
  load_worktree_setup

  generate_override

  # A failed boot leaves the worktree in place on purpose: the cause is usually
  # a fixable env/config problem, and re-running spawn would refuse because the
  # directory now exists. Point at both ways out instead of silently dying.
  if ! compose up -d --wait; then
    echo >&2
    echo "error: stack failed to start; worktree and branch were kept." >&2
    echo "  retry:   cd $DIR && COMPOSE_PROJECT_NAME=$PROJECT ${COMPOSE_WRAPPER:+$COMPOSE_WRAPPER }docker compose up -d --wait" >&2
    echo "  discard: worktree.sh teardown $branch" >&2
    exit 1
  fi

  echo
  echo "worktree: $DIR"
  echo "project:  $PROJECT"
  compose ps --format json \
    | jq -r '.Publishers[]? | select(.PublishedPort > 0)
             | "\(.TargetPort) -> http://localhost:\(.PublishedPort)"' \
    | sort -u
}

cmd_teardown() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh teardown <branch>"
  require git docker

  resolve "$branch"
  [ -d "$DIR" ] || die "no worktree at $DIR"

  if [ -n "$(dirty "$DIR")" ]; then
    die "$branch has uncommitted changes in $DIR — commit, stash, or remove manually"
  fi

  cd "$DIR"
  # Same contract as spawn: without the wrapper, `compose down` cannot read a
  # compose file that interpolates injected env, and the `|| true` below would
  # swallow that and silently leak containers and volumes.
  load_worktree_setup
  COMPOSE_PROJECT_NAME="$PROJECT" compose down -v --remove-orphans || true

  cd "$ROOT"
  git worktree remove --force "$DIR"
  git branch -D "$branch" 2>/dev/null || true

  echo "removed $branch — cd back to $ROOT"
}

# -------------------------------------------------------------- dispatch ---

case "${1:-help}" in
  spawn)            shift; cmd_spawn "$@" ;;
  teardown|down)    shift; cmd_teardown "$@" ;;
  reap)             shift; cmd_reap ;;
  list|ls)          shift; cmd_list ;;
  help|-h|--help)   usage ;;
  *)                echo "unknown command: $1" >&2; echo >&2; usage >&2; exit 1 ;;
esac
